//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2012.02.03 at 05:40:14 PM MEZ 
//


package org.oasis.ebxml.registry.bindings.spi;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the oasis.names.tc.ebxml_regrep.xsd.spi._4 package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: oasis.names.tc.ebxml_regrep.xsd.spi._4
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link FilteringExceptionType }
     * 
     */
    public FilteringExceptionType createFilteringExceptionType() {
        return new FilteringExceptionType();
    }

    /**
     * Create an instance of {@link ValidateObjectsRequest }
     * 
     */
    public ValidateObjectsRequest createValidateObjectsRequest() {
        return new ValidateObjectsRequest();
    }

    /**
     * Create an instance of {@link ValidateObjectsResponse }
     * 
     */
    public ValidateObjectsResponse createValidateObjectsResponse() {
        return new ValidateObjectsResponse();
    }

    /**
     * Create an instance of {@link ValidationExceptionType }
     * 
     */
    public ValidationExceptionType createValidationExceptionType() {
        return new ValidationExceptionType();
    }

    /**
     * Create an instance of {@link FilterObjectsRequest }
     * 
     */
    public FilterObjectsRequest createFilterObjectsRequest() {
        return new FilterObjectsRequest();
    }

    /**
     * Create an instance of {@link FilterObjectsResponse }
     * 
     */
    public FilterObjectsResponse createFilterObjectsResponse() {
        return new FilterObjectsResponse();
    }

    /**
     * Create an instance of {@link CatalogingExceptionType }
     * 
     */
    public CatalogingExceptionType createCatalogingExceptionType() {
        return new CatalogingExceptionType();
    }

    /**
     * Create an instance of {@link CatalogObjectsRequest }
     * 
     */
    public CatalogObjectsRequest createCatalogObjectsRequest() {
        return new CatalogObjectsRequest();
    }

    /**
     * Create an instance of {@link CatalogObjectsResponse }
     * 
     */
    public CatalogObjectsResponse createCatalogObjectsResponse() {
        return new CatalogObjectsResponse();
    }

}
